### ISSUE TITLE
Compile Issue Example Project for up-rust v0.1.5

### ISSUE THREAD

**Issue by ext-lumen-dennis-grewe** [eclipse-uprotocol/up-zenoh-example-rust#9]
Hi folks,

we are running in a compile issue since today where it seems the provided up-rust version 0.1.5 is not available for compilation anymore. Please find attached a screenshot of the compile issue:

<img width="1119" alt="up_zenoh_rust_example-issue" src="https://github.com/eclipse-uprotocol/up-zenoh-example-rust/assets/167969025/f122909e-454c-40c7-bfc3-8bfcae6835ca">

Maybe related to the latest changes in the up-rust repository: [3a50104421a801d52e1d9c68979db54c013ce43d](https://github.com/eclipse-uprotocol/up-rust/commit/3a50104421a801d52e1d9c68979db54c013ce43d)

Best regards
Dennis

**Comment by evshary** [comment]
Hi @ext-lumen-dennis-grewe I think this should be fixed now. Thanks for your report!
